on:
  push:
    branches: [ main, 26-03-02-actions ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install libsdl2-dev

      - name: initialize CMake
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          mkdir build
          cmake -B build -GNinja

      - name: initialize CMake (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build
          cmake -B build -GNinja

      - name: build
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cmake --build build

      - name: build (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build build

      # TODO: Run tests?